theme: jekyll-theme-cayman
title: SSCQC Support
description: The Self-Taught Computational Quantum Chemistry
github:
  is_project_page: false
url: "https://ryokokuga.github.io/SSCQC/"
plugins:
 - jekyll-sitemap
 
<head><meta name="google-site-verification" content="ynMrKc1L_JKIqJyIO3AYmPsVWd5OrYRu-2ARTrFVmsw" /></head>
